# Change the values of the following keys to match your own configuration


# This should be the location of a selenium driver for the browser you want to use 
# (e.g. chromedriver for Chrome, geckodriver for Firefox)
# See: https://chromedriver.chromium.org/getting-started
binary_location: "/Applications/Firefox Developer Edition.app/Contents/MacOS/firefox"


# This should be the path to the Excel file you want to read
# Example:
xlsx_path: "/Users/shaananc/Library/CloudStorage/OneDrive-Personal/useful-scripts/arc_budget/output/spreadsheet/DP27-Budget-Reconstructed.xlsx"

# This should be the name of the sheet in the Excel file that contains the budget data
sheet_name: '2. DP27 Budget Tool'


# These values likely don't need to be changed
proposal_id: "DP270101107"
year_columns:
  - C
  - J
  - Q
  - X
  - AE

row_configs:
  - start_row: 15
    end_row: 20
    category: PERSONNEL

  - start_row: 48
    end_row: 50
    category: TRAVEL

  # - start_row: 38
  #   end_row: 47
  #   category: FIELD_RESEARCH

  # - start_row: 49
  #   end_row: 58
  #   category: MAINTENANCE

  - start_row: 130
    end_row: 134
    category: OTHER

in_kind: True
teaching_relief: False
clear_first: True
